title: exatrines.github.io
description: exatrines docs
theme: just-the-docs

url: https://exatrines.github.io/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/exatrines/exatrines.github.io